"""Report rendering for batch evaluations."""

from __future__ import annotations

from .trace_schema import SafeAIResult


def render_markdown_report(results: list[tuple[dict[str, object], SafeAIResult]]) -> str:
    lines = [
        "# ELUZA Safe AI Tool Batch Report",
        "",
        "This report is generated by the public-safe standalone tool. It does not",
        "include private ELUZA core source, private memory, raw data, or internal logic.",
        "",
        "| ID | Fruit | Status | Allowed | Risk | Next Route |",
        "|---|---|---|---|---|---|",
    ]
    for case, result in results:
        case_id = str(case.get("id", "case"))
        lines.append(
            f"| {case_id} | {result.fruit_type} | {result.status} | "
            f"{str(result.allowed).lower()} | {result.risk} | {result.next_route} |"
        )

    lines.extend(["", "## Details", ""])
    for case, result in results:
        case_id = str(case.get("id", "case"))
        lines.extend(
            [
                f"### {case_id}",
                "",
                f"- Reason: {result.reason}",
                f"- Safe boundary: {result.safe_boundary}",
                f"- Mizan: {result.mizan_status}",
                f"- Answer mode: {result.answer_mode}",
                "",
            ]
        )
    return "\n".join(lines)

